#!/usr/bin/bash -x
#this is a first attempt at creating a simple install script
#	"install" is probably a bit generous, this will be ran after an arch install to setup a basic rice(hopefully)
#
#

echo Please enter your root/sudo password
read -s varpw

expect << EOF
	exp_internal 1
	set user "$USER"
	set password "$varpw"
	puts "User: $user"
	puts "PW: $password"


	spawn sudo pacman -S fastfetch hyprlock hyprpaper nvim rofi nodejs waybar zsh nwg-look firefox nemo
	expect "\\[sudo\\] password for $user"
	send "$password\r"

	spawn sudo pacman -S nerd-fonts
	expect "\\[sudo\\] password for $user"
	send "$password\r"
	expect "Enter a selection (default=all):"
	send "22\r"

	spawn sudo pacman -S nerd-fonts
	expect "\\[sudo\\] password for $user"
	send "$password\r"
	expect "Enter a selection (default=all):"
	send "63\r"

	spawn sh -c "curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh"
	expect "Do you want to change your default shell to zsh? \[Y/n\]"
	send "Y\r"
	expect "\\[sudo\\] password for $user"
	send "$password\r"
	expect eof
EOF


mkdir -p ~/Pictures
mkdir -p ~/.icons
mkdir -p ~/.themes

#this will attempt to determine the display being used and set it accordingly
#in hyprland.conf and hyprpaper.conf
monname=$(hyprctl monitors all | grep Monitor | cut -d ' ' -f 2)
monres=$(hyprctl monitors all | sed '2!d' | cut -d ' ' -f 1)



sed -i -e "s/Virtual-1/$monname/g" dotconfig/hypr/hyprpaper.conf
sed -i -e "s/Virtual-1/$monname/g" dotconfig/hypr/hyprland.conf
sed -i -e "s/1920x1080/$monres/g" dotconfig/hypr/hyprland.conf



cp -r dotconfig/* ~/.config/
cp -r doticons/* ~/.icons/
cp -r dotthemes/* ~/.themes/
cp .zshrc ~/
cp -r Pictures/* ~/Pictures

echo done....
